run:
  timeout: 5m
output:
  formats:
    - format: colored-line-number
linters:
  enable-all: false
  disable-all: true
  enable:
    - vet
    - goimports
    - thelper
    - unconvert
    - revive
    - unused
    - gofmt
    - misspell
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
severity:
  default-severity: error