project_name: shield
release:
  prerelease: auto
before:
  hooks:
    - make test
builds:
  - id: "shield"
    main: ./main.go
    binary: shield
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/goto/shield/config.Version={{.Tag}}
      - -X github.com/goto/shield/config.BuildCommit={{.FullCommit}}
      - -X github.com/goto/shield/config.BuildDate={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm, 386, arm64]
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Os "windows" }}windows
      {{- else if eq .Arch "linux" }}linux
      {{- else if eq .Arch "darwin" }}macos
      {{- else }}{{ .Arch }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^build"
      - "^chore"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - shield
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/gotocompany/{{.ProjectName}}:latest"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Tag }}-amd64"
nfpms:
  - maintainer: gotocompany
    description: Identity and authorization system
    homepage: https://github.com/goto/shield
    license: Apache 2.0
    formats:
      - deb
      - rpm
scoop:
  bucket:
    owner: goto
    name: scoop-bucket
  homepage: "https://github.com/goto/shield"
  description: "Identity and authorization system"
  license: Apache 2.0
brews:
  - name: shield
    homepage: "https://github.com/goto/shield"
    description: "Identity and authorization system"
    tap:
      owner: goto
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "shield"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com