with-expecter: True
packages:
  github.com/goto/shield/internal/api/v1beta1:
    config:
      dir: "internal/api/v1beta1/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      ActionService:
        config:
          filename: "action_service.go"
      ActivityService:
        config:
          filename: "activity_service.go"
      GroupService:
        config:
          filename: "group_service.go"
      NamespaceService:
        config:
          filename: "namespace_service.go"
      OrganizationService:
        config:
          filename: "organization_service.go"
      PolicyService:
        config:
          filename: "policy_service.go"
      ProjectService:
        config:
          filename: "project_service.go"
      RelationService:
        config:
          filename: "relation_service.go"
      ResourceService:
        config:
          filename: "resource_service.go"
      RoleService:
        config:
          filename: "role_service.go"
      RuleService:
        config:
          filename: "rule_service.go"
      ServiceDataService:
        config:
          filename: "servicedata_service.go"
      UserService:
        config:
          filename: "user_service.go"
      RelationTransformer:
        config:
          filename: "relation_transformer.go"
  github.com/goto/shield/internal/proxy/hook/authz:
    config:
      dir: "internal/proxy/hook/authz/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      ResourceService:
        config:
          filename: "resource_service.go"
      RelationService:
        config:
          filename: "relation_service.go"
      RelationTransformer:
        config:
          filename: "relation_transformer.go"
  github.com/goto/shield/core/action:
    config:
      dir: "core/action/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      Repository:
        config:
          filename: "action_repository.go"
      UserService:
        config:
          filename: "user_service.go"
      ActivityService:
        config:
          filename: "activity_service.go"
  github.com/goto/shield/core/policy:
    config:
      dir: "core/policy/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      Repository:
        config:
          filename: "policy_repository.go"
      UserService:
        config:
          filename: "user_service.go"
      ActivityService:
        config:
          filename: "activity_service.go"
  github.com/goto/shield/core/role:
    config:
      dir: "core/role/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      Repository:
        config:
          filename: "role_repository.go"
      UserService:
        config:
          filename: "user_service.go"
      ActivityService:
        config:
          filename: "activity_service.go"
  github.com/goto/shield/core/user:
    config:
      dir: "core/user/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      ActivityService:
        config:
          filename: "activity_service.go"
      Repository:
        config:
          filename: "user_repository.go"
  github.com/goto/shield/core/group:
    config:
      dir: "core/group/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      ActivityService:
        config:
          filename: "activity_service.go"
      RelationService:
        config:
          filename: "relation_service.go"
      UserService:
        config:
          filename: "user_service.go"
      Repository:
        config:
          filename: "group_repository.go"
      CachedRepository:
        config:
          filename: "cached_group_repository.go"
  github.com/goto/shield/core/relation:
    config:
      dir: "core/relation/mocks"
      outpkg: "mocks"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      UserService:
        config:
          filename: user_service.go
      ActivityService:
        config:
          filename: activity_service.go
      Repository:
        config: 
          filename: relation_repository.go
      AuthzRepository:
        config: 
          filename: authz_repository.go
  github.com/goto/shield/core/servicedata:
    config:
      dir: "core/servicedata/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      UserService:
        config:
          filename: "user_service.go"
      RelationService:
        config:
          filename: "relation_service.go"
      ProjectService:
        config:
          filename: "project_service.go"
      ResourceService:
        config:
          filename: "resource_service.go"
      ActivityService:
        config:
          filename: "activity_service.go"
      Repository:
        config:
          filename: "servicedata_repository.go"
  github.com/goto/shield/internal/store/inmemory:
    config:
      dir: "internal/store/inmemory/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      GroupRepository:
        config:
          filename: "group_repository.go"
  github.com/goto/shield/internal/proxy/envoy/xds/ads:
    config:
      dir: "internal/proxy/envoy/xds/ads/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      Repository:
        config:
          filename: "repository.go"
  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3:
    config:
      dir: "internal/proxy/envoy/xds/ads/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      AggregatedDiscoveryService_StreamAggregatedResourcesServer:
        config:
          filename: "ads_stream.go"