with-expecter: True
packages:
  github.com/goto/shield/internal/api/v1beta1:
    config:
      dir: "internal/api/v1beta1/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      ActionService:
        config:
          filename: "action_service.go"
      ActivityService:
        config:
          filename: "activity_service.go"
      GroupService:
        config:
          filename: "group_service.go"
      NamespaceService:
        config:
          filename: "namespace_service.go"
      OrganizationService:
        config:
          filename: "organization_service.go"
      PolicyService:
        config:
          filename: "policy_service.go"
      ProjectService:
        config:
          filename: "project_service.go"
      RelationService:
        config:
          filename: "relation_service.go"
      ResourceService:
        config:
          filename: "resource_service.go"
      RoleService:
        config:
          filename: "role_service.go"
      RuleService:
        config:
          filename: "rule_service.go"
      UserService:
        config:
          filename: "user_service.go"
      RelationTransformer:
        config:
          filename: "relation_transformer.go"
  github.com/goto/shield/internal/proxy/hook/authz:
    config:
      dir: "internal/proxy/hook/authz/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      ResourceService:
        config:
          filename: "resource_service.go"
      RelationService:
        config:
          filename: "relation_service.go"
      RelationTransformer:
        config:
          filename: "relation_transformer.go"
  github.com/goto/shield/core/user:
    config:
      dir: "core/mocks"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
    interfaces: 
      ActivityService:
        config:
          filename: "activity_service.go"
      Repository:
        config:
          filename: "user_repository.go"