version: "3.7"

services:
  pg:
    image: gotocompany/postgres-partman:1.0.0
    environment:
      - POSTGRES_DB=shield
      - POSTGRES_USER=shield
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shield"]
      interval: 30s
      timeout: 30s
      retries: 3
    command:       [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr",
        "-c",
        "shared_preload_libraries=pg_cron",
        "-c",
        "cron.database_name=shield",
      ]
  
  pg2:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "spicedb"
      POSTGRES_DB: "spicedb"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./temp/pgdata2:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spicedb"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  spicedb:
    image: authzed/spicedb:v1.2.0
    ports:
      - "8080:8080"
      - "50051:50051"
      - "50053:50053"
    command:
      serve --grpc-preshared-key "shield" --datastore-engine postgres --datastore-conn-uri postgres://spicedb:@pg2:5432/spicedb?sslmode=disable
    restart: on-failure
    depends_on:
      pg2:
        condition: service_healthy
      spicedb-migration:
        condition: service_completed_successfully

  spicedb-migration:
    image: authzed/spicedb:v1.2.0
    command: migrate head --datastore-engine postgres --datastore-conn-uri postgres://spicedb:@pg2:5432/spicedb?sslmode=disable
    restart: on-failure
    depends_on:
      pg2:
        condition: service_healthy