// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: gotocompany/shield/v1beta1/public.proto

package shieldv1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShieldPublicService_UpdateUserServiceData_FullMethodName  = "/gotocompany.shield.v1beta1.ShieldPublicService/UpdateUserServiceData"
	ShieldPublicService_UpdateGroupServiceData_FullMethodName = "/gotocompany.shield.v1beta1.ShieldPublicService/UpdateGroupServiceData"
)

// ShieldPublicServiceClient is the client API for ShieldPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShieldPublicServiceClient interface {
	UpdateUserServiceData(ctx context.Context, in *UpdateUserServiceDataRequest, opts ...grpc.CallOption) (*UpdateUserServiceDataResponse, error)
	UpdateGroupServiceData(ctx context.Context, in *UpdateGroupServiceDataRequest, opts ...grpc.CallOption) (*UpdateGroupServiceDataResponse, error)
}

type shieldPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShieldPublicServiceClient(cc grpc.ClientConnInterface) ShieldPublicServiceClient {
	return &shieldPublicServiceClient{cc}
}

func (c *shieldPublicServiceClient) UpdateUserServiceData(ctx context.Context, in *UpdateUserServiceDataRequest, opts ...grpc.CallOption) (*UpdateUserServiceDataResponse, error) {
	out := new(UpdateUserServiceDataResponse)
	err := c.cc.Invoke(ctx, ShieldPublicService_UpdateUserServiceData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shieldPublicServiceClient) UpdateGroupServiceData(ctx context.Context, in *UpdateGroupServiceDataRequest, opts ...grpc.CallOption) (*UpdateGroupServiceDataResponse, error) {
	out := new(UpdateGroupServiceDataResponse)
	err := c.cc.Invoke(ctx, ShieldPublicService_UpdateGroupServiceData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShieldPublicServiceServer is the server API for ShieldPublicService service.
// All implementations must embed UnimplementedShieldPublicServiceServer
// for forward compatibility
type ShieldPublicServiceServer interface {
	UpdateUserServiceData(context.Context, *UpdateUserServiceDataRequest) (*UpdateUserServiceDataResponse, error)
	UpdateGroupServiceData(context.Context, *UpdateGroupServiceDataRequest) (*UpdateGroupServiceDataResponse, error)
	mustEmbedUnimplementedShieldPublicServiceServer()
}

// UnimplementedShieldPublicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShieldPublicServiceServer struct {
}

func (UnimplementedShieldPublicServiceServer) UpdateUserServiceData(context.Context, *UpdateUserServiceDataRequest) (*UpdateUserServiceDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserServiceData not implemented")
}
func (UnimplementedShieldPublicServiceServer) UpdateGroupServiceData(context.Context, *UpdateGroupServiceDataRequest) (*UpdateGroupServiceDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupServiceData not implemented")
}
func (UnimplementedShieldPublicServiceServer) mustEmbedUnimplementedShieldPublicServiceServer() {}

// UnsafeShieldPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShieldPublicServiceServer will
// result in compilation errors.
type UnsafeShieldPublicServiceServer interface {
	mustEmbedUnimplementedShieldPublicServiceServer()
}

func RegisterShieldPublicServiceServer(s grpc.ServiceRegistrar, srv ShieldPublicServiceServer) {
	s.RegisterService(&ShieldPublicService_ServiceDesc, srv)
}

func _ShieldPublicService_UpdateUserServiceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserServiceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShieldPublicServiceServer).UpdateUserServiceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShieldPublicService_UpdateUserServiceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShieldPublicServiceServer).UpdateUserServiceData(ctx, req.(*UpdateUserServiceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShieldPublicService_UpdateGroupServiceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupServiceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShieldPublicServiceServer).UpdateGroupServiceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShieldPublicService_UpdateGroupServiceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShieldPublicServiceServer).UpdateGroupServiceData(ctx, req.(*UpdateGroupServiceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShieldPublicService_ServiceDesc is the grpc.ServiceDesc for ShieldPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShieldPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotocompany.shield.v1beta1.ShieldPublicService",
	HandlerType: (*ShieldPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUserServiceData",
			Handler:    _ShieldPublicService_UpdateUserServiceData_Handler,
		},
		{
			MethodName: "UpdateGroupServiceData",
			Handler:    _ShieldPublicService_UpdateGroupServiceData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gotocompany/shield/v1beta1/public.proto",
}
