// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gotocompany/shield/v1beta1/public.proto

package shieldv1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ServiceDataKeyRequestBody with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ServiceDataKeyRequestBody) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceDataKeyRequestBody with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServiceDataKeyRequestBodyMultiError, or nil if none found.
func (m *ServiceDataKeyRequestBody) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceDataKeyRequestBody) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Project

	// no validation rules for Key

	// no validation rules for Description

	if len(errors) > 0 {
		return ServiceDataKeyRequestBodyMultiError(errors)
	}

	return nil
}

// ServiceDataKeyRequestBodyMultiError is an error wrapping multiple validation
// errors returned by ServiceDataKeyRequestBody.ValidateAll() if the
// designated constraints aren't met.
type ServiceDataKeyRequestBodyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceDataKeyRequestBodyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceDataKeyRequestBodyMultiError) AllErrors() []error { return m }

// ServiceDataKeyRequestBodyValidationError is the validation error returned by
// ServiceDataKeyRequestBody.Validate if the designated constraints aren't met.
type ServiceDataKeyRequestBodyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceDataKeyRequestBodyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceDataKeyRequestBodyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceDataKeyRequestBodyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceDataKeyRequestBodyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceDataKeyRequestBodyValidationError) ErrorName() string {
	return "ServiceDataKeyRequestBodyValidationError"
}

// Error satisfies the builtin error interface
func (e ServiceDataKeyRequestBodyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceDataKeyRequestBody.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceDataKeyRequestBodyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceDataKeyRequestBodyValidationError{}

// Validate checks the field values on ServiceDataKey with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ServiceDataKey) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceDataKey with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ServiceDataKeyMultiError,
// or nil if none found.
func (m *ServiceDataKey) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceDataKey) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Urn

	// no validation rules for Id

	if len(errors) > 0 {
		return ServiceDataKeyMultiError(errors)
	}

	return nil
}

// ServiceDataKeyMultiError is an error wrapping multiple validation errors
// returned by ServiceDataKey.ValidateAll() if the designated constraints
// aren't met.
type ServiceDataKeyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceDataKeyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceDataKeyMultiError) AllErrors() []error { return m }

// ServiceDataKeyValidationError is the validation error returned by
// ServiceDataKey.Validate if the designated constraints aren't met.
type ServiceDataKeyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceDataKeyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceDataKeyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceDataKeyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceDataKeyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceDataKeyValidationError) ErrorName() string { return "ServiceDataKeyValidationError" }

// Error satisfies the builtin error interface
func (e ServiceDataKeyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceDataKey.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceDataKeyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceDataKeyValidationError{}

// Validate checks the field values on CreateServiceDataKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateServiceDataKeyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateServiceDataKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateServiceDataKeyRequestMultiError, or nil if none found.
func (m *CreateServiceDataKeyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateServiceDataKeyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBody()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateServiceDataKeyRequestValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateServiceDataKeyRequestValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateServiceDataKeyRequestValidationError{
				field:  "Body",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateServiceDataKeyRequestMultiError(errors)
	}

	return nil
}

// CreateServiceDataKeyRequestMultiError is an error wrapping multiple
// validation errors returned by CreateServiceDataKeyRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateServiceDataKeyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateServiceDataKeyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateServiceDataKeyRequestMultiError) AllErrors() []error { return m }

// CreateServiceDataKeyRequestValidationError is the validation error returned
// by CreateServiceDataKeyRequest.Validate if the designated constraints
// aren't met.
type CreateServiceDataKeyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateServiceDataKeyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateServiceDataKeyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateServiceDataKeyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateServiceDataKeyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateServiceDataKeyRequestValidationError) ErrorName() string {
	return "CreateServiceDataKeyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateServiceDataKeyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateServiceDataKeyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateServiceDataKeyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateServiceDataKeyRequestValidationError{}

// Validate checks the field values on CreateServiceDataKeyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateServiceDataKeyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateServiceDataKeyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateServiceDataKeyResponseMultiError, or nil if none found.
func (m *CreateServiceDataKeyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateServiceDataKeyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetServiceDataKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateServiceDataKeyResponseValidationError{
					field:  "ServiceDataKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateServiceDataKeyResponseValidationError{
					field:  "ServiceDataKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetServiceDataKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateServiceDataKeyResponseValidationError{
				field:  "ServiceDataKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateServiceDataKeyResponseMultiError(errors)
	}

	return nil
}

// CreateServiceDataKeyResponseMultiError is an error wrapping multiple
// validation errors returned by CreateServiceDataKeyResponse.ValidateAll() if
// the designated constraints aren't met.
type CreateServiceDataKeyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateServiceDataKeyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateServiceDataKeyResponseMultiError) AllErrors() []error { return m }

// CreateServiceDataKeyResponseValidationError is the validation error returned
// by CreateServiceDataKeyResponse.Validate if the designated constraints
// aren't met.
type CreateServiceDataKeyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateServiceDataKeyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateServiceDataKeyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateServiceDataKeyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateServiceDataKeyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateServiceDataKeyResponseValidationError) ErrorName() string {
	return "CreateServiceDataKeyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateServiceDataKeyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateServiceDataKeyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateServiceDataKeyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateServiceDataKeyResponseValidationError{}

// Validate checks the field values on UpdateServiceDataRequestBody with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateServiceDataRequestBody) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateServiceDataRequestBody with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateServiceDataRequestBodyMultiError, or nil if none found.
func (m *UpdateServiceDataRequestBody) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateServiceDataRequestBody) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Project

	if len(m.GetData()) != 1 {
		err := UpdateServiceDataRequestBodyValidationError{
			field:  "Data",
			reason: "value must contain exactly 1 pair(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateServiceDataRequestBodyMultiError(errors)
	}

	return nil
}

// UpdateServiceDataRequestBodyMultiError is an error wrapping multiple
// validation errors returned by UpdateServiceDataRequestBody.ValidateAll() if
// the designated constraints aren't met.
type UpdateServiceDataRequestBodyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateServiceDataRequestBodyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateServiceDataRequestBodyMultiError) AllErrors() []error { return m }

// UpdateServiceDataRequestBodyValidationError is the validation error returned
// by UpdateServiceDataRequestBody.Validate if the designated constraints
// aren't met.
type UpdateServiceDataRequestBodyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateServiceDataRequestBodyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateServiceDataRequestBodyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateServiceDataRequestBodyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateServiceDataRequestBodyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateServiceDataRequestBodyValidationError) ErrorName() string {
	return "UpdateServiceDataRequestBodyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateServiceDataRequestBodyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateServiceDataRequestBody.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateServiceDataRequestBodyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateServiceDataRequestBodyValidationError{}

// Validate checks the field values on UpdateUserServiceDataRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserServiceDataRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserServiceDataRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserServiceDataRequestMultiError, or nil if none found.
func (m *UpdateUserServiceDataRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserServiceDataRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetBody()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateUserServiceDataRequestValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateUserServiceDataRequestValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateUserServiceDataRequestValidationError{
				field:  "Body",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateUserServiceDataRequestMultiError(errors)
	}

	return nil
}

// UpdateUserServiceDataRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateUserServiceDataRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateUserServiceDataRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserServiceDataRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserServiceDataRequestMultiError) AllErrors() []error { return m }

// UpdateUserServiceDataRequestValidationError is the validation error returned
// by UpdateUserServiceDataRequest.Validate if the designated constraints
// aren't met.
type UpdateUserServiceDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserServiceDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserServiceDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserServiceDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserServiceDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserServiceDataRequestValidationError) ErrorName() string {
	return "UpdateUserServiceDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserServiceDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserServiceDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserServiceDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserServiceDataRequestValidationError{}

// Validate checks the field values on UpdateGroupServiceDataRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGroupServiceDataRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGroupServiceDataRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateGroupServiceDataRequestMultiError, or nil if none found.
func (m *UpdateGroupServiceDataRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGroupServiceDataRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetBody()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateGroupServiceDataRequestValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateGroupServiceDataRequestValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateGroupServiceDataRequestValidationError{
				field:  "Body",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateGroupServiceDataRequestMultiError(errors)
	}

	return nil
}

// UpdateGroupServiceDataRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateGroupServiceDataRequest.ValidateAll()
// if the designated constraints aren't met.
type UpdateGroupServiceDataRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGroupServiceDataRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGroupServiceDataRequestMultiError) AllErrors() []error { return m }

// UpdateGroupServiceDataRequestValidationError is the validation error
// returned by UpdateGroupServiceDataRequest.Validate if the designated
// constraints aren't met.
type UpdateGroupServiceDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGroupServiceDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGroupServiceDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGroupServiceDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGroupServiceDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGroupServiceDataRequestValidationError) ErrorName() string {
	return "UpdateGroupServiceDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGroupServiceDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGroupServiceDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGroupServiceDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGroupServiceDataRequestValidationError{}

// Validate checks the field values on UpdateUserServiceDataResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserServiceDataResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserServiceDataResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateUserServiceDataResponseMultiError, or nil if none found.
func (m *UpdateUserServiceDataResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserServiceDataResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Urn

	if len(errors) > 0 {
		return UpdateUserServiceDataResponseMultiError(errors)
	}

	return nil
}

// UpdateUserServiceDataResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateUserServiceDataResponse.ValidateAll()
// if the designated constraints aren't met.
type UpdateUserServiceDataResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserServiceDataResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserServiceDataResponseMultiError) AllErrors() []error { return m }

// UpdateUserServiceDataResponseValidationError is the validation error
// returned by UpdateUserServiceDataResponse.Validate if the designated
// constraints aren't met.
type UpdateUserServiceDataResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserServiceDataResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserServiceDataResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserServiceDataResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserServiceDataResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserServiceDataResponseValidationError) ErrorName() string {
	return "UpdateUserServiceDataResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserServiceDataResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserServiceDataResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserServiceDataResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserServiceDataResponseValidationError{}

// Validate checks the field values on UpdateGroupServiceDataResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGroupServiceDataResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGroupServiceDataResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateGroupServiceDataResponseMultiError, or nil if none found.
func (m *UpdateGroupServiceDataResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGroupServiceDataResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Urn

	if len(errors) > 0 {
		return UpdateGroupServiceDataResponseMultiError(errors)
	}

	return nil
}

// UpdateGroupServiceDataResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateGroupServiceDataResponse.ValidateAll()
// if the designated constraints aren't met.
type UpdateGroupServiceDataResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGroupServiceDataResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGroupServiceDataResponseMultiError) AllErrors() []error { return m }

// UpdateGroupServiceDataResponseValidationError is the validation error
// returned by UpdateGroupServiceDataResponse.Validate if the designated
// constraints aren't met.
type UpdateGroupServiceDataResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGroupServiceDataResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGroupServiceDataResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGroupServiceDataResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGroupServiceDataResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGroupServiceDataResponseValidationError) ErrorName() string {
	return "UpdateGroupServiceDataResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGroupServiceDataResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGroupServiceDataResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGroupServiceDataResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGroupServiceDataResponseValidationError{}
