// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gotocompany/shield/v1beta1/public.proto

package shieldv1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListUserResourcesByTypeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserResourcesByTypeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserResourcesByTypeRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListUserResourcesByTypeRequestMultiError, or nil if none found.
func (m *ListUserResourcesByTypeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserResourcesByTypeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Namespace

	// no validation rules for Type

	if len(errors) > 0 {
		return ListUserResourcesByTypeRequestMultiError(errors)
	}

	return nil
}

// ListUserResourcesByTypeRequestMultiError is an error wrapping multiple
// validation errors returned by ListUserResourcesByTypeRequest.ValidateAll()
// if the designated constraints aren't met.
type ListUserResourcesByTypeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserResourcesByTypeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserResourcesByTypeRequestMultiError) AllErrors() []error { return m }

// ListUserResourcesByTypeRequestValidationError is the validation error
// returned by ListUserResourcesByTypeRequest.Validate if the designated
// constraints aren't met.
type ListUserResourcesByTypeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserResourcesByTypeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserResourcesByTypeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserResourcesByTypeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserResourcesByTypeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserResourcesByTypeRequestValidationError) ErrorName() string {
	return "ListUserResourcesByTypeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListUserResourcesByTypeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUserResourcesByTypeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUserResourcesByTypeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserResourcesByTypeRequestValidationError{}

// Validate checks the field values on ListUserResourcesByTypeResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserResourcesByTypeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserResourcesByTypeResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListUserResourcesByTypeResponseMultiError, or nil if none found.
func (m *ListUserResourcesByTypeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserResourcesByTypeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResources()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUserResourcesByTypeResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUserResourcesByTypeResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResources()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUserResourcesByTypeResponseValidationError{
				field:  "Resources",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListUserResourcesByTypeResponseMultiError(errors)
	}

	return nil
}

// ListUserResourcesByTypeResponseMultiError is an error wrapping multiple
// validation errors returned by ListUserResourcesByTypeResponse.ValidateAll()
// if the designated constraints aren't met.
type ListUserResourcesByTypeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserResourcesByTypeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserResourcesByTypeResponseMultiError) AllErrors() []error { return m }

// ListUserResourcesByTypeResponseValidationError is the validation error
// returned by ListUserResourcesByTypeResponse.Validate if the designated
// constraints aren't met.
type ListUserResourcesByTypeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserResourcesByTypeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserResourcesByTypeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserResourcesByTypeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserResourcesByTypeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserResourcesByTypeResponseValidationError) ErrorName() string {
	return "ListUserResourcesByTypeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListUserResourcesByTypeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUserResourcesByTypeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUserResourcesByTypeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserResourcesByTypeResponseValidationError{}
