// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	group "github.com/goto/shield/core/group"
	mock "github.com/stretchr/testify/mock"
)

// CachedRepository is an autogenerated mock type for the CachedRepository type
type CachedRepository struct {
	mock.Mock
}

type CachedRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CachedRepository) EXPECT() *CachedRepository_Expecter {
	return &CachedRepository_Expecter{mock: &_m.Mock}
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *CachedRepository) GetBySlug(ctx context.Context, slug string) (group.Group, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (group.Group, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) group.Group); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(group.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CachedRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type CachedRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *CachedRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *CachedRepository_GetBySlug_Call {
	return &CachedRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *CachedRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *CachedRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CachedRepository_GetBySlug_Call) Return(_a0 group.Group, _a1 error) *CachedRepository_GetBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CachedRepository_GetBySlug_Call) RunAndReturn(run func(context.Context, string) (group.Group, error)) *CachedRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// NewCachedRepository creates a new instance of CachedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCachedRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CachedRepository {
	mock := &CachedRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
