name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: install dependencies
        run: go mod tidy
      - name: test binaries
        env:
          POSTGRES_PASSWORD: postgres
        run: make test
      - name: Send coverage to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
  e2e-smoke-test:
    runs-on: ubuntu-latest
    services:
      echo-server:
        image: ealen/echo-server
        ports:
          - "4000:80"
      spicedb:
        image: authzed/spicedb:v1.32.0
        ports:
          - "8080:8080"
          - "50051:50051"
          - "50053:50053"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: install dependencies
        run: go mod tidy
      - name: install spicedb binary
        uses: authzed/action-spicedb@v1
      - name: run proxy tests
        env:
          POSTGRES_PASSWORD: postgres
        run: make e2e-smoke-test
        